- name: Update PATH in bashrc
  ansible.builtin.lineinfile:
    path: /etc/bashrc
    line: 'export PATH=$PATH:/opt/kafka/bin'
    state: present
    create: yes
    backup: yes

- name: Install confluent-kafka
  ansible.builtin.pip:
    name: confluent-kafka
    executable: pip3
  when: inventory_hostname in groups['producer']

- name: Install kafka-python
  ansible.builtin.pip:
    name: kafka-python
    executable: pip3
  when: inventory_hostname in groups['producer']

- name: Configure Zookeeper properties
  ansible.builtin.blockinfile:
    path: /opt/kafka/config/zookeeper.properties
    block: |
      initLimit=10
      syncLimit=5
      server.1=s1:2888:3888
      server.2=s2:2888:3888
      server.3=s3:2888:3888
    state: present
    create: yes
    backup: yes

- name: Ensure /data directory exists
  ansible.builtin.file:
    path: /data
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create myid file
  ansible.builtin.copy:
    dest: /data/myid
    content: "{{ groups['consumer'].index(inventory_hostname) + 1 }}"
  when: inventory_hostname in groups['consumer']

- name: Configure Kafka server properties
  ansible.builtin.lineinfile:
    path: /opt/kafka/config/server.properties
    line: |
      zookeeper.connect=s1:2181,s2:2181,s3:2181
    state: present
    create: yes
    backup: yes

- name: Set unique broker ID
  ansible.builtin.lineinfile:
    path: /opt/kafka/config/server.properties
    line: "broker.id={{ item }}"
    state: present
  loop:
    - "1"
    - "2"
    - "3"
