# roles/hadoop/tasks/configure_hadoop.yml

- name: Configure core-site.xml
  template:
    src: core-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/core-site.xml

- name: Configure hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/hdfs-site.xml

- name: Set JAVA_HOME in hadoop-env.sh
  lineinfile:
    path: /opt/hadoop/etc/hadoop/hadoop-env.sh
    line: 'export JAVA_HOME=/usr/lib/jvm/jre-openjdk'
    create: yes

# 네임노드에만 적용
- name: Create NameNode directory
  file:
    path: /opt/hadoop/dfs/name
    state: directory
    mode: '0755'
  when: "'namenodes' in group_names"

# 데이터노드에만 적용
- name: Create DataNode directory
  file:
    path: /opt/hadoop/dfs/data
    state: directory
    mode: '0755'
  when: "'datanodes' in group_names"
