- name: Configure core-site.xml
  template:
    src: core-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/core-site.xml

- name: Configure hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/hdfs-site.xml

- name: Configure mapred-site.xml
  template:
    src: mapred-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/mapred-site.xml

- name: Configure yarn-site.xml
  template:
    src: yarn-site.xml.j2
    dest: /opt/hadoop/etc/hadoop/yarn-site.xml

- name: Ensure Hadoop path is in root's .bashrc
  lineinfile:
    path: /root/.bashrc
    line: "export PATH=$PATH:/opt/hadoop/bin"
    state: present
